apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnap-dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: cnap-server
    newName: cnap-registry:5000/cnap-server  # k3d local registry
    newTag: dev

commonLabels:
  environment: local
