apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnap-dev-temp

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: cnap-server
    newName: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}
    newTag: temp-latest

commonLabels:
  environment: temp
